title:            La Quête
tagline:          La Quête
description:      Quêtes et dragons. Bienvenue dans le monde de Coline.
canonical:        https://la-quete.thuault.com

# Owner/author information
owner:
  name:           Thuault Clément
  email:          thuaultc@gmail.com
  github:         thuaultc
  location:       "Paris, FR"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Carte
    url: /carte
  - title: Personnages
    url: /personnages

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title.html

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
